### ISSUE TITLE
Subreddit display must be minimal, with larger picture.

### ISSUE THREAD

**Issue by Microflow** [Microflow/fforward-android#1]
This app will display a list of mealsharing, clothes-sharing and citizen trash collection links. For now, we will use the  /r/art subreddit to fix the design.

This screenshot is a little large, but shows the fields that need to disappear.

![Screenshot](https://lh3.googleusercontent.com/-772VgOLOdJ0/WwgG_waTcOI/AAAAAAAACxA/4THwpuUXTegFV6YnhpaOHhbXnyp1cVH7wCL0BGAYYCw/h1920/Screenshot_20180525-205023.png "Screenshot")

- The picture for each link needs to be bigger. Please find where we can change the height and width of the picture. A square pic is best for now. 

### Some fields need to be taken out, for a more minimal design. 
Please remove the following fields:
- Points (pts)
- Number of comments.
- Author (by)

And show how to remove these fields.

#### The following files may help:

Check lines 137-143

https://github.com/Microflow/buy-some-give-one-android/blob/2210513e4ae5ff062892f88811c843ce714c5fa1/src/main/java/org/quantumbadger/redreader/views/RedditPostHeaderView.java

General image info here:

https://github.com/Microflow/buy-some-give-one-android/tree/2210513e4ae5ff062892f88811c843ce714c5fa1/src/main/java/org/quantumbadger/redreader/image

Image views:

https://github.com/Microflow/buy-some-give-one-android/tree/2210513e4ae5ff062892f88811c843ce714c5fa1/src/main/java/org/quantumbadger/redreader/views/imageview

Maybe image size renderers here:

https://github.com/Microflow/buy-some-give-one-android/blob/2210513e4ae5ff062892f88811c843ce714c5fa1/src/main/java/org/quantumbadger/redreader/views/imageview/BoundsHelper.java

https://github.com/Microflow/buy-some-give-one-android/blob/2210513e4ae5ff062892f88811c843ce714c5fa1/src/main/java/org/quantumbadger/redreader/image/ThumbnailScaler.java

**Comment by skyevil12** [comment]
@Microflow 
How about if I enlarge the thumbnail size to twice larger?

Current way is scale down the image to 64dp*64dp and put it in center of imageview.
You could check [dp converter](https://pixplicity.com/dp-px-converter) for size reference.

**Comment by Microflow** [comment]
Twice larger is good. Im wondering if Reddit scale down the image
themselves, or if its scaled down by the app. If it can be doubled in size,
and still look ok, we can try that.

Aligning it in the center of the page, over the text, is good.

Feel free to change the design according to your own intuition.

**Comment by skyevil12** [comment]
Issue closed due to PR #12
