### ISSUE TITLE
Raleway font for display.

### ISSUE THREAD

**Issue by Microflow** [Microflow/fforward-android#3]
If it isn't too costly, I'd like to use Raleway font, weight 200, with Century Gothic as a fallback.

https://stackoverflow.com/questions/44733184/what-are-the-different-ways-to-change-font-style-in-android-studio

https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts

**Comment by skyevil12** [comment]
Per discussed, I would help to remove other language and keep english, traditional chinese and simplified.
Also apply Raleway light font(weight 300) to all text fields  within this app.

**Comment by Microflow** [comment]
Sure. Please don't remove other languages. We will display in Raleway or
Montserrat for English and Chinese. Other languages can display in their
default fonts.

If you have any ideas how to improve the typeface without increasing the
size of the app, I am listening.

**Comment by skyevil12** [comment]
To use custom font without increasing size of the app, downloadable font feature could support this.
The second [link](https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts) you provided explain this in detail.

**Comment by Microflow** [comment]
I will check that link out. I don't mind increasing size by 0.5MB for 1-2
languages, but any more is a hassle for the user.

I would also like to give the user a choice of fonts later. But for the
beta version, one font is fine.

**Comment by Microflow** [comment]
The downloadable font option looks good. Are there any tradeoffs or
downsides? There are 3 ways to incorporate it.


   - via Android Studio and Google Play Services
   <https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts#via-android-studio>
   - Programmatically
   <https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts#programmatically>
   - Via the support library
   <https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts#via-support-lib>

Which do you recommend?

**Comment by priyankakendrekar** [comment]
Font files

src/main/java/org/quantumbadger/redreader/views/PostListingHeader.java

`final Typeface tf = Typeface.createFromAsset(context.getAssets(), "fonts/Roboto-Light.ttf");
`
src/main/java/org/quantumbadger/redreader/views/RedditPostHeaderView.java




`final Typeface tf = Typeface.createFromAsset(activity.getAssets(), "fonts/Raleway-Thin.ttf");
`

src/main/java/org/quantumbadger/redreader/common/General.java



```
if(monoTypeface == null) {
  monoTypeface = Typeface.createFromAsset(context.getAssets(), "fonts/VeraMono.ttf");
}

```

**Comment by Microflow** [comment]
Some interesting answers here:

https://stackoverflow.com/questions/16404820/how-to-set-default-font-family-for-entire-android-app

**Comment by Microflow** [comment]
Recommended by Eric:

https://segunfamisa.com/posts/custom-fonts-with-android-support-library
